<a href="https://colab.research.google.com/github/fabricioramosdev/TensorFlow_Machine_Learning/blob/master/multiplicacao_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow.compat.v1 as tf

In [0]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[-1,3],[4,2]])

In [0]:
multiplicacao = tf.matmul(a,b)

In [8]:
with tf.Session() as sess:
  print(sess.run(a))
  print('\n')
  print(sess.run(b))
  print('\n')
  print(sess.run(multiplicacao))

[[1 2]
 [3 4]]


[[-1  3]
 [ 4  2]]


[[ 7  7]
 [13 17]]


In [12]:
multiplicacao2 = tf.matmul(b,a)
with tf.Session() as sess:
  print(sess.run(multiplicacao2))

[[ 8 10]
 [10 16]]


In [15]:
a1 = tf.constant([[2,3],[0,1],[-1,4]])
b1 = tf.constant([[1,2,3],[-2,0,4]])
multiplicacao3 = tf.matmul(a1,b1)
with tf.Session() as sess:
  print(sess.run(a1))
  print('\n')
  print(sess.run(b1))
  print('\n')
  print(sess.run(multiplicacao3))

[[ 2  3]
 [ 0  1]
 [-1  4]]


[[ 1  2  3]
 [-2  0  4]]


[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]
